### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by Slava** [mit6148-staff/website#4]
Just my notes that I took checking out the website

1. Capitalization of names on `/team/` is inconsistent, for example Alex Chen's name is capitalized, most people's is not
2. The names on `/team/` are difficult to read. Maybe add a black shadow for text, or a gradient background on the bottom?
3. A lot of older links on the `/winners/` page are dead, we should try to find github links for source code instead for ones like Skiary
4. Some screenshots of `/winners/` are real sad, we should either replace with a placeholder (if it is too old) or take a new quality screenshot manually
5. The layout of `/` breaks on the short screen size (see screenshot)
6. The text of quotes is hard to read on `/`, especially on mouse-hover

<img width="1440" alt="screen shot 2018-09-09 at 9 41 55 pm" src="https://user-images.githubusercontent.com/2608446/45272076-32bba180-b479-11e8-94ab-e88e9874d058.png">

**Comment by jynnie** [comment]
These are great catches. Responding to feedback:
1. Agree, will make them all lowercase by default through CSS
2. I'll look into experimenting with this. Is this problem mostly with the black and white photos?
3. Agree, we can also remove links to dead sites
4. Agree
5. Thanks for the catch, will fix. 
6. Agree, should be fixed in latest commit. Would like more feedback on the newer display.
